# -*- coding: utf-8 -*-
"""currncy-convrter-app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S7M9f5yyrepsC40m2UAbFPXu39UxEV4F
"""

# Install required libraries
!pip install gradio requests

import gradio as gr
import requests

# Function to get currency rates
def get_rates(base="USD"):
    url = f"https://open.er-api.com/v6/latest/{base}"
    try:
        resp = requests.get(url, timeout=5)
        resp.raise_for_status()
        data = resp.json()
        if data.get("result") != "success":
            return None, f"API error: {data.get('error-type')}"
        return data.get("rates", {}), None
    except Exception as e:
        return None, str(e)

# Function to convert currency
def convert_currency(amount, from_currency, to_currency):
    rates, error = get_rates(from_currency.upper())
    if error:
        return f"Error: {error}"
    if to_currency.upper() not in rates:
        return f"Currency {to_currency} not found!"
    converted_amount = amount * rates[to_currency.upper()]
    return f"{amount} {from_currency.upper()} = {converted_amount:.2f} {to_currency.upper()}"

# Gradio interface
iface = gr.Interface(
    fn=convert_currency,
    inputs=[
        gr.Number(label="Amount"),
        gr.Textbox(label="From Currency (e.g., USD)"),
        gr.Textbox(label="To Currency (e.g., PKR)")
    ],
    outputs="text",
    title="Currency Converter",
    description="Convert amount from one currency to another in real-time!"
)

# Launch the app (share=True generates a public link)
iface.launch(share=True)